spring:
  application:
    name: microservice-order
    microservice-customer:
      url: http://localhost:8090/customer/api/v1/
  main:
    allow-bean-definition-overriding: true


  devtools:
    restart:
      enabled: true
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: order

server:
  port: 8090
  servlet:
    context-path: /order