spring:
  application:
    name: microservice-order

    microservice-customer:
      url: http://aa62f80b9596a4fa6835d80a506227d6-1183908486.eu-central-1.elb.amazonaws.com/customer/api/v1/

  data:
    mongodb:
      uri: mongodb+srv://mkmongouser:Secret@clustermicroservice.fzatn.mongodb.net
      database: order

server:
  port: 8080
  servlet:
    context-path: /order